### PR TITLE
Update PPPL portal makefiles option

### PR DESCRIPTION
**Pull request by zhucaoxiang**
I have updated the makefiles for PPPL portal. To use it, just load the `stellopt/develop_intel` module.

### CODE REVIEW

**Comment by amollen** [comment]
In makefile.portal there are some comments I wrote for Eddy, e.g. about Petsc. I guess those instructions won't work on Portal? If so can you please remove them.

**Comment by zhucaoxiang** [comment]
@amollen Sure, I will update the Makefile. By the way, I found the variable `PETSC_ARCH` is not defined either on PPPL or on Eddy. I removed that line in the makefile and nothing happened.

**Comment by amollen** [comment]
Yes it depends on how Petsc has been installed (or how you set PETSC_DIR). In the makefile there is a flag EXTRA_COMPILE_FLAGS which contains possible paths to the Petsc installation. As long as one of the paths works it should be fine.

**Comment by zhucaoxiang** [comment]
@amollen I have removed irrelevant comments.

**Pull request merged**
